server:
  port: 8888
spring:
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/danielocanaheredia/spring-cloud-config-files
          search-paths:
            - 'station*'
security:
  basic:
    enabled: true
  user:
    name: root
    password: root